# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/dev/osmium

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/dev/osmium

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/osmium/CMakeFiles /mnt/c/dev/osmium/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/osmium/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osmium

# Build rule for target.
osmium: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osmium
.PHONY : osmium

# fast build rule for target.
osmium/fast:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/build
.PHONY : osmium/fast

src/config/config.o: src/config/config.cpp.o

.PHONY : src/config/config.o

# target to build an object file
src/config/config.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/config/config.cpp.o
.PHONY : src/config/config.cpp.o

src/config/config.i: src/config/config.cpp.i

.PHONY : src/config/config.i

# target to preprocess a source file
src/config/config.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/config/config.cpp.i
.PHONY : src/config/config.cpp.i

src/config/config.s: src/config/config.cpp.s

.PHONY : src/config/config.s

# target to generate assembly for a file
src/config/config.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/config/config.cpp.s
.PHONY : src/config/config.cpp.s

src/editor/editor.o: src/editor/editor.cpp.o

.PHONY : src/editor/editor.o

# target to build an object file
src/editor/editor.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/editor/editor.cpp.o
.PHONY : src/editor/editor.cpp.o

src/editor/editor.i: src/editor/editor.cpp.i

.PHONY : src/editor/editor.i

# target to preprocess a source file
src/editor/editor.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/editor/editor.cpp.i
.PHONY : src/editor/editor.cpp.i

src/editor/editor.s: src/editor/editor.cpp.s

.PHONY : src/editor/editor.s

# target to generate assembly for a file
src/editor/editor.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/editor/editor.cpp.s
.PHONY : src/editor/editor.cpp.s

src/editor/format.o: src/editor/format.cpp.o

.PHONY : src/editor/format.o

# target to build an object file
src/editor/format.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/editor/format.cpp.o
.PHONY : src/editor/format.cpp.o

src/editor/format.i: src/editor/format.cpp.i

.PHONY : src/editor/format.i

# target to preprocess a source file
src/editor/format.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/editor/format.cpp.i
.PHONY : src/editor/format.cpp.i

src/editor/format.s: src/editor/format.cpp.s

.PHONY : src/editor/format.s

# target to generate assembly for a file
src/editor/format.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/editor/format.cpp.s
.PHONY : src/editor/format.cpp.s

src/graphics/text.o: src/graphics/text.cpp.o

.PHONY : src/graphics/text.o

# target to build an object file
src/graphics/text.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/graphics/text.cpp.o
.PHONY : src/graphics/text.cpp.o

src/graphics/text.i: src/graphics/text.cpp.i

.PHONY : src/graphics/text.i

# target to preprocess a source file
src/graphics/text.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/graphics/text.cpp.i
.PHONY : src/graphics/text.cpp.i

src/graphics/text.s: src/graphics/text.cpp.s

.PHONY : src/graphics/text.s

# target to generate assembly for a file
src/graphics/text.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/graphics/text.cpp.s
.PHONY : src/graphics/text.cpp.s

src/graphics/window.o: src/graphics/window.cpp.o

.PHONY : src/graphics/window.o

# target to build an object file
src/graphics/window.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/graphics/window.cpp.o
.PHONY : src/graphics/window.cpp.o

src/graphics/window.i: src/graphics/window.cpp.i

.PHONY : src/graphics/window.i

# target to preprocess a source file
src/graphics/window.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/graphics/window.cpp.i
.PHONY : src/graphics/window.cpp.i

src/graphics/window.s: src/graphics/window.cpp.s

.PHONY : src/graphics/window.s

# target to generate assembly for a file
src/graphics/window.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/graphics/window.cpp.s
.PHONY : src/graphics/window.cpp.s

src/input/input.o: src/input/input.cpp.o

.PHONY : src/input/input.o

# target to build an object file
src/input/input.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/input/input.cpp.o
.PHONY : src/input/input.cpp.o

src/input/input.i: src/input/input.cpp.i

.PHONY : src/input/input.i

# target to preprocess a source file
src/input/input.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/input/input.cpp.i
.PHONY : src/input/input.cpp.i

src/input/input.s: src/input/input.cpp.s

.PHONY : src/input/input.s

# target to generate assembly for a file
src/input/input.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/input/input.cpp.s
.PHONY : src/input/input.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tab/tab.o: src/tab/tab.cpp.o

.PHONY : src/tab/tab.o

# target to build an object file
src/tab/tab.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/tab/tab.cpp.o
.PHONY : src/tab/tab.cpp.o

src/tab/tab.i: src/tab/tab.cpp.i

.PHONY : src/tab/tab.i

# target to preprocess a source file
src/tab/tab.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/tab/tab.cpp.i
.PHONY : src/tab/tab.cpp.i

src/tab/tab.s: src/tab/tab.cpp.s

.PHONY : src/tab/tab.s

# target to generate assembly for a file
src/tab/tab.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/tab/tab.cpp.s
.PHONY : src/tab/tab.cpp.s

src/tab/tablist.o: src/tab/tablist.cpp.o

.PHONY : src/tab/tablist.o

# target to build an object file
src/tab/tablist.cpp.o:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/tab/tablist.cpp.o
.PHONY : src/tab/tablist.cpp.o

src/tab/tablist.i: src/tab/tablist.cpp.i

.PHONY : src/tab/tablist.i

# target to preprocess a source file
src/tab/tablist.cpp.i:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/tab/tablist.cpp.i
.PHONY : src/tab/tablist.cpp.i

src/tab/tablist.s: src/tab/tablist.cpp.s

.PHONY : src/tab/tablist.s

# target to generate assembly for a file
src/tab/tablist.cpp.s:
	$(MAKE) -f CMakeFiles/osmium.dir/build.make CMakeFiles/osmium.dir/src/tab/tablist.cpp.s
.PHONY : src/tab/tablist.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... osmium"
	@echo "... src/config/config.o"
	@echo "... src/config/config.i"
	@echo "... src/config/config.s"
	@echo "... src/editor/editor.o"
	@echo "... src/editor/editor.i"
	@echo "... src/editor/editor.s"
	@echo "... src/editor/format.o"
	@echo "... src/editor/format.i"
	@echo "... src/editor/format.s"
	@echo "... src/graphics/text.o"
	@echo "... src/graphics/text.i"
	@echo "... src/graphics/text.s"
	@echo "... src/graphics/window.o"
	@echo "... src/graphics/window.i"
	@echo "... src/graphics/window.s"
	@echo "... src/input/input.o"
	@echo "... src/input/input.i"
	@echo "... src/input/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tab/tab.o"
	@echo "... src/tab/tab.i"
	@echo "... src/tab/tab.s"
	@echo "... src/tab/tablist.o"
	@echo "... src/tab/tablist.i"
	@echo "... src/tab/tablist.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

